const svg = d3.select("#svg-chart-area").append("svg")
  .attr("width", 500)
  .attr("height", 400)
  .style("border", "0.5px solid black")


svg.append('line')
  .attr('x1', 10)
  .attr('y1', 10)
  .attr('x2', 10)
  .attr('y2', 390)
  .attr('stroke', 'red')

svg.append('rect')
  .attr('x', 50)
  .attr('y', 10)
  .attr('width', 200)
  .attr('height', 380)
  .attr('stroke', 'black')
  .attr('fill', '#69a3b2')

svg.append("ellipse")
  .attr("cx", 400)
  .attr("cy", 200)
  .attr("rx", 50)
  .attr("ry", 100)
  .attr('stroke', 'black')
  .attr('fill', '#69a3b2')
